apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones the datapower source repository builds an image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  - name: shared-data-1
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: fetch-source-1
    runAfter: ["fetch-source"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data-1
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: "pipelines"
  - name: build-push
    runAfter: ["fetch-source-1"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: $(params.image-reference)
  - name: run-dp-task1
    runAfter: ["build-push"]
    taskRef:
      name: dp-task01
    workspaces:
    - name: source
      workspace: shared-data
    - name: source-1
      workspace: shared-data-1
